url = 'https://getpocket.com/v3/get'
consumer_key = ''
access_token = ''
repertoire = 'data'
temporisation = 15000
config_log = 'config/log4rs.yml'
sauvegarde = 10

[rechargement]
date_debut = ''
dates=[]
nb_jours=0
nb_parcourt=0



